##
#  This compose file is used for local development and adapter testing only.
#  See `/docker` for a generic and production-ready docker file
##

version: "3.5"
services:

  dbt:
    #build: .
    build:
      context: ./dockerfiles
      dockerfile: dbt.Dockerfile
    command: --version
    ports:
      - '888:8080' # Only for docs server --> Terminal/CMD > docker-compose run --service-ports dbt docs serve
    volumes:
      - ./dbt:/usr/app/
      - ./dbt_profile:/root/.dbt/
    #working_dir: /usr/app

networks:
  default:
    name: ohdsi-2022-hub